import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Gift, Search, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { offersApi } from '../api/offers.api';

export default function OffersPage(){
 const qc=useQueryClient(); const [search,setSearch]=useState('');
 const {data:offers=[],isLoading}=useQuery({queryKey:['admin-offers'],queryFn:offersApi.getAll});
 const status=useMutation({mutationFn:({id,active}:{id:number;active:boolean})=>offersApi.setStatus(id,active),onSuccess:()=>qc.invalidateQueries({queryKey:['admin-offers']})});
 const remove=useMutation({mutationFn:offersApi.remove,onSuccess:()=>qc.invalidateQueries({queryKey:['admin-offers']})});
 const filtered=offers.filter(o=>`${o.title} ${o.workshopName} ${o.serviceNames||''}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="space-y-5"><div><h1 className="text-2xl font-bold text-surface-900 dark:text-white">الباقات والعروض</h1><p className="text-sm text-surface-500">مراجعة وإدارة عروض جميع الورش</p></div>
 <div className="grid grid-cols-3 gap-3"><div className="card p-4"><p className="text-xs text-surface-500">الإجمالي</p><strong className="text-2xl">{offers.length}</strong></div><div className="card p-4"><p className="text-xs text-surface-500">نشطة</p><strong className="text-2xl text-emerald-600">{offers.filter(o=>o.isActive).length}</strong></div><div className="card p-4"><p className="text-xs text-surface-500">موقوفة</p><strong className="text-2xl text-red-600">{offers.filter(o=>!o.isActive).length}</strong></div></div>
 <div className="relative"><Search className="absolute right-3 top-1/2 -translate-y-1/2 text-surface-400" size={17}/><input className="input-field pr-10" value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث باسم العرض أو الورشة..."/></div>
 {isLoading?<div className="card h-40 animate-pulse"/>:filtered.length===0?<div className="card p-12 text-center"><Gift className="mx-auto text-surface-300" size={40}/><p className="mt-3 font-bold">لا توجد عروض</p></div>:<div className="card overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-surface-500"><th className="p-3 text-right">العرض</th><th className="p-3 text-right">الورشة</th><th className="p-3">السعر</th><th className="p-3">المدة</th><th className="p-3">الحالة</th><th className="p-3">إجراء</th></tr></thead><tbody>{filtered.map(o=><tr key={o.id} className="border-b border-surface-100 dark:border-surface-800"><td className="p-3"><b>{o.title}</b><p className="text-xs text-surface-500">{o.serviceNames}</p></td><td className="p-3">{o.workshopName}<p className="text-xs text-surface-400">{o.workshopCity}</p></td><td className="p-3 text-center"><b>{o.offerPrice} ر.س</b>{o.originalPrice?<p className="text-xs line-through text-surface-400">{o.originalPrice}</p>:null}</td><td className="p-3 text-center text-xs">{o.startDate||'مفتوح'} — {o.endDate||'مفتوح'}</td><td className="p-3 text-center"><button onClick={()=>status.mutate({id:o.id,active:!o.isActive})} className={`rounded-full px-3 py-1 text-xs font-bold ${o.isActive?'bg-emerald-100 text-emerald-700':'bg-red-100 text-red-700'}`}>{o.isActive?'نشط':'موقوف'}</button></td><td className="p-3 text-center"><button onClick={()=>confirm('حذف العرض نهائيًا؟')&&remove.mutate(o.id)} className="text-red-500"><Trash2 size={17}/></button></td></tr>)}</tbody></table></div>}</div>;
}
