import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import QRCode from 'qrcode';

const esc = (v: unknown) => String(v ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]!));
const sar = (v: unknown) => `${Number(v || 0).toLocaleString('ar-SA', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ر.س`;
const rows = (items: any[], label = 'name') => (items || []).map((x, i) => `<tr><td>${i + 1}. ${esc(x[label])}</td><td>${x.quantity ?? x.hours ?? 1}</td><td>${sar(x.unitPrice ?? x.hourlyRate)}</td><td>${sar(x.total)}</td></tr>`).join('');

async function download(title: string, subtitle: string, meta: string, body: string, filename: string) {
  const host = document.createElement('div');
  host.style.cssText = 'position:fixed;left:-10000px;top:0;background:#fff';
  host.innerHTML = `<main dir="rtl" style="width:794px;min-height:1123px;padding:44px;font-family:Cairo,Tahoma,Arial;color:#171717;background:#fff;box-sizing:border-box"><style>@font-face{font-family:Cairo;src:url('/fonts/cairo.woff2')}*{box-sizing:border-box}.h{display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid #e30613;padding-bottom:20px}.b{display:flex;align-items:center;gap:12px}.b img{width:65px;height:65px;object-fit:contain;border-radius:14px}.b strong{font-size:25px}.t{text-align:left}.t h1{font-size:21px;margin:0}.t p,.muted{font-size:10px;color:#777}.meta{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:20px 0}.meta div{border:1px solid #ddd;border-radius:10px;padding:9px;font-size:10px}.meta small{display:block;color:#888}.parties{display:grid;grid-template-columns:1fr 1fr;gap:10px}.party{background:#f7f7f7;border-radius:12px;padding:13px;font-size:11px}.party b{display:block;font-size:13px}h2{font-size:14px;border-right:4px solid #e30613;padding-right:9px;margin-top:20px}table{width:100%;border-collapse:collapse;font-size:10px}th{background:#171717;color:#fff;padding:10px}td{padding:9px;border-bottom:1px solid #eee;text-align:center}th:first-child,td:first-child{text-align:right}.totals{width:52%;margin-right:auto;margin-top:15px}.r{display:flex;justify-content:space-between;padding:8px;border-bottom:1px solid #eee;font-size:11px}.final{background:#e30613;color:#fff;border-radius:9px;font-size:14px;font-weight:900}.note{margin-top:14px;background:#fff5f5;border:1px solid #ffd0d3;border-radius:10px;padding:10px;color:#7f1d1d;font-size:10px}.footer{position:absolute;bottom:35px;right:44px;left:44px;border-top:1px solid #ddd;padding-top:12px;display:flex;justify-content:space-between;color:#888;font-size:9px}</style><header class="h"><div class="b"><img src="/tasaheel-logo.png"><div><strong>تساهيل</strong><div class="muted">منصة صيانة السيارات</div></div></div><div class="t"><h1>${title}</h1><p>${subtitle}</p></div></header><div class="meta">${meta}</div>${body}<footer class="footer"><span>وثيقة إلكترونية صادرة عبر منصة تساهيل</span><span>salabaa.com</span></footer></main>`;
  document.body.appendChild(host);
  try { await document.fonts.ready; await new Promise(r => setTimeout(r, 100)); const canvas = await html2canvas(host.firstElementChild as HTMLElement, { scale: 2, useCORS: true, backgroundColor: '#fff' }); const pdf = new jsPDF('p', 'mm', 'a4'); const w = pdf.internal.pageSize.getWidth(); pdf.addImage(canvas.toDataURL('image/jpeg', .96), 'JPEG', 0, 0, w, canvas.height * w / canvas.width); pdf.save(filename); } finally { host.remove(); }
}

export async function exportInvoicePdf(invoice: any, request: any) {
  const vat = Number(invoice.taxPercent ?? 15), total = Number(invoice.grandTotal || 0), base = Number(invoice.totalAmount ?? total / (1 + vat / 100)), tax = Number(invoice.taxAmount ?? invoice.tax ?? total - base);
  const qr = invoice.zatcaQrPayload ? await QRCode.toDataURL(invoice.zatcaQrPayload, { width: 150, margin: 1, errorCorrectionLevel: 'M' }) : '';
  const meta = `<div><small>رقم الفاتورة</small><b>${esc(invoice.invoiceNumber || invoice.id)}</b></div><div><small>رقم الطلب</small><b>${esc(request.requestNumber || request.id)}</b></div><div><small>تاريخ الإصدار</small><b>${new Date(invoice.createdAt).toLocaleDateString('ar-SA-u-ca-gregory')}</b></div><div><small>الحالة</small><b>${esc(invoice.status)}</b></div>`;
  const body = `<div class="parties"><div class="party"><b>مقدم الخدمة</b>${esc(invoice.supplierLegalName || invoice.workshopName || 'ورشة تساهيل')}<br>${esc(invoice.supplierAddress || '')}<br>الرقم الضريبي: ${esc(invoice.supplierTaxNumber || 'غير مسجل')}<br>السجل التجاري: ${esc(invoice.supplierCommercialRegistration || '—')}</div><div class="party"><b>العميل والمركبة</b>${esc(request.customerName || 'عميل تساهيل')}<br>${esc([request.carMake, request.carModel, request.carYear].filter(Boolean).join(' ') || '—')}${qr ? `<br><img src="${qr}" style="width:92px;height:92px;margin-top:8px" alt="QR ضريبي">` : ''}</div></div><h2>تفاصيل البنود</h2><table><thead><tr><th>البيان</th><th>الكمية</th><th>سعر الوحدة شامل الضريبة</th><th>الإجمالي</th></tr></thead><tbody>${rows(invoice.items)}</tbody></table><div class="totals"><div class="r"><span>الإجمالي قبل الضريبة</span><b>${sar(base)}</b></div><div class="r"><span>ضريبة القيمة المضافة (${vat}%)</span><b>${sar(tax)}</b></div><div class="r final"><span>الإجمالي النهائي</span><span>${sar(total)}</span></div></div><div class="note">أسعار البنود شاملة ضريبة القيمة المضافة، وتم استخراج الضريبة من الإجمالي.</div>`;
  await download('فاتورة ضريبية مبسطة', 'فاتورة خدمات صيانة سيارات', meta, body, `فاتورة-تساهيل-${invoice.invoiceNumber || request.id}.pdf`);
}

export async function exportInspectionPdf(report: any, request: any) {
  const meta = `<div><small>رقم التقرير</small><b>${esc(report.reportNumber || report.id)}</b></div><div><small>رقم الطلب</small><b>${esc(request.requestNumber || request.id)}</b></div><div><small>تاريخ الفحص</small><b>${new Date(report.createdAt).toLocaleDateString('ar-SA-u-ca-gregory')}</b></div><div><small>الأولوية</small><b>${esc(report.priority || 'عادية')}</b></div>`;
  const body = `<div class="parties"><div class="party"><b>الورشة</b>${esc(request.workshopName || 'ورشة تساهيل')}</div><div class="party"><b>المركبة</b>${esc([request.carMake, request.carModel, request.carYear].filter(Boolean).join(' ') || '—')}</div></div>${report.parts?.length ? `<h2>قطع الغيار المقترحة</h2><table><thead><tr><th>البيان</th><th>الكمية</th><th>سعر الوحدة</th><th>الإجمالي</th></tr></thead><tbody>${rows(report.parts)}</tbody></table>` : ''}${report.labor?.length ? `<h2>أعمال الصيانة</h2><table><thead><tr><th>العمل</th><th>الساعات</th><th>سعر الساعة</th><th>الإجمالي</th></tr></thead><tbody>${rows(report.labor, 'description')}</tbody></table>` : ''}<h2>ملاحظات الفني</h2><div class="party">${esc(report.notes || 'لا توجد ملاحظات إضافية.')}</div><div class="totals"><div class="r final"><span>التكلفة التقديرية</span><span>${sar(report.grandTotal)}</span></div></div>`;
  await download('تقرير فحص فني', 'نتائج الفحص والتوصيات الفنية', meta, body, `تقرير-فحص-تساهيل-${request.id}.pdf`);
}

export async function exportCustomerTablePdf(title: string, filename: string, headers: string[], data: unknown[][], summary?: string) {
  const meta = `<div><small>تاريخ الإصدار</small><b>${new Date().toLocaleString('ar-SA-u-ca-gregory')}</b></div><div><small>عدد السجلات</small><b>${data.length}</b></div>`;
  const body = `<h2>${esc(title)}</h2><table><thead><tr>${headers.map(h => `<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${data.map(row => `<tr>${row.map(value => `<td>${esc(value)}</td>`).join('')}</tr>`).join('')}</tbody></table>${summary ? `<div class="note">${esc(summary)}</div>` : ''}`;
  await download(title, 'مستند صادر من حساب العميل', meta, body, `${filename}.pdf`);
}

export async function exportPaymentReceiptPdf(payment: any, requestId: string | number) {
  const meta = `<div><small>رقم العملية</small><b>${esc(payment.id || payment.paymentId || '—')}</b></div><div><small>رقم الطلب</small><b>#${esc(requestId)}</b></div><div><small>تاريخ الدفع</small><b>${new Date(payment.paidAt || payment.updatedAt || Date.now()).toLocaleString('ar-SA-u-ca-gregory')}</b></div><div><small>الحالة</small><b>${esc(payment.status || 'completed')}</b></div>`;
  const body = `<div class="parties"><div class="party"><b>نوع المستند</b>إيصال سداد إلكتروني</div><div class="party"><b>طريقة الدفع</b>${esc(payment.method || payment.paymentMethod || 'دفع إلكتروني')}</div></div><div class="totals"><div class="r final"><span>المبلغ المدفوع</span><span>${sar(payment.total || payment.amount)}</span></div></div><div class="note">هذا الإيصال يثبت نجاح عملية الدفع للطلب المشار إليه، ولا يحل محل الفاتورة الضريبية.</div>`;
  await download('إيصال دفع', 'تأكيد تحصيل إلكتروني', meta, body, `إيصال-دفع-تساهيل-${requestId}.pdf`);
}
