ALTER TABLE media ALTER COLUMN type TYPE TEXT;
ALTER TABLE media ALTER COLUMN url TYPE TEXT;
ALTER TABLE media ALTER COLUMN thumbnail_url TYPE TEXT;
ALTER TABLE media ADD COLUMN IF NOT EXISTS original_file_name TEXT;
ALTER TABLE media ADD COLUMN IF NOT EXISTS mime_type TEXT;
ALTER TABLE media ADD COLUMN IF NOT EXISTS file_size BIGINT;

ALTER TABLE workshop_gallery ALTER COLUMN media_url TYPE TEXT;
ALTER TABLE workshop_gallery ALTER COLUMN media_type TYPE TEXT;
