package com.tasaheel.event;

public enum EventType {
    REQUEST_CREATED,
    REQUEST_SUBMITTED,
    REQUEST_CANCELLED,
    QUOTE_GENERATED,
    QUOTE_ACCEPTED,
    QUOTE_REJECTED,
    OFFER_ACCEPTED,
    OFFER_SELECTED,
    JOB_SPLIT_CREATED,
    WORKSHOP_ASSIGNED,
    STATUS_UPDATED,
    SERVICE_STARTED,
    SERVICE_COMPLETED,
    SERVICE_VERIFIED,
    REPORT_SUBMITTED,
    REPORT_APPROVED,
    REPORT_REJECTED,
    INVOICE_CREATED,
    INVOICE_APPROVED,
    PAYMENT_INITIATED,
    PAYMENT_HELD,
    PAYMENT_RELEASED,
    PAYMENT_REFUNDED,
    ADMIN_OVERRIDE,
    WORKSHOP_REASSIGNED
}
