import {
  Droplet, Wind, PlugZap, Cog, Fuel, Gauge,
  Wrench, Settings, Car, Battery, Zap, Thermometer,
  CircleDot, Circle, Disc, RotateCcw, ArrowDownUp,
  Shield, Truck, AlertTriangle, Key, Lightbulb,
  Volume2, Lock, PaintBucket, Eraser,
  GlassWater, Eye, Sun, Fan,
  CircleDotDashed, Hammer,
  type LucideIcon,
} from 'lucide-react';

export const SERVICE_ICON_MAP: Record<string, LucideIcon> = {
  'oil-drop': Droplet,
  'air-filter': Wind,
  'ac-filter': Wind,
  'spark-plug': PlugZap,
  'gearbox-oil': Cog,
  'brake-fluid': Droplet,
  'coolant': Droplet,
  'inspection': Gauge,
  'belt': RotateCcw,
  'fuel-filter': Fuel,
  'engine-overhaul': Wrench,
  'head-gasket': Wrench,
  'oil-pump': Droplet,
  'water-pump': Droplet,
  'engine-mount': CircleDot,
  'timing': RotateCcw,
  'oil-leak': Droplet,
  'injector': CircleDot,
  'o2-sensor': Circle,
  'fuel-pump': Fuel,
  'auto-gearbox': Cog,
  'manual-gearbox': Cog,
  'clutch': Disc,
  'transfer-case': Cog,
  'differential': Cog,
  'driveshaft': ArrowDownUp,
  'shock': CircleDotDashed,
  'spring': CircleDotDashed,
  'ball-joint': Circle,
  'control-arm': ArrowDownUp,
  'tie-rod': ArrowDownUp,
  'axle': ArrowDownUp,
  'brake-front': Disc,
  'brake-rear': Disc,
  'brake-pump': Droplet,
  'brake-cylinder': Circle,
  'alternator': Zap,
  'starter': Zap,
  'battery': Battery,
  'coil': Zap,
  'ecu': Settings,
  'sensor': Circle,
  'wiring': Zap,
  'bulb': Lightbulb,
  'audio': Volume2,
  'alarm': Lock,
  'ac-gas': Thermometer,
  'ac-compressor': Thermometer,
  'thermostat': Thermometer,
  'radiator-fan': Fan,
  'radiator': Thermometer,
  'ac-pump': Thermometer,
  'radiator-flush': Thermometer,
  'ac-evaporator': Thermometer,
  'dent': Hammer,
  'paint': PaintBucket,
  'full-paint': PaintBucket,
  'filler': Eraser,
  'polish': Sun,
  'glass': GlassWater,
  'tint': Eye,
  'tow': Truck,
  'tire': Circle,
  'fuel': Fuel,
  'unlock': Key,
  'jump-start': Zap,
  'transport': Truck,
};

export function getServiceIcon(slug: string | null | undefined, fallback: LucideIcon = Wrench): LucideIcon {
  if (!slug) return fallback;
  return SERVICE_ICON_MAP[slug] || fallback;
}
