
create table accounts (
balance float(53) not null,
is_active boolean not null,
is_system boolean not null,
level integer not null,
created_at timestamp(6),
id bigint generated by default as identity,
parent_id bigint,
updated_at timestamp(6),
code varchar(20) not null unique,
type varchar(20) not null,
name varchar(255) not null,
name_en varchar(255),
primary key (id)
);

create table chat_messages (
is_read boolean not null,
created_at timestamp(6),
id bigint generated by default as identity,
room_id bigint not null,
sender_id bigint not null,
content TEXT not null,
media_url varchar(255),
sender_role varchar(255) not null,
type varchar(255) not null,
primary key (id)
);

create table chat_rooms (
created_at timestamp(6),
customer_id bigint not null,
driver_id bigint,
id bigint generated by default as identity,
request_id bigint not null,
workshop_id bigint,
primary key (id)
);

create table customer_cars (
car_year integer not null,
created_at timestamp(6),
customer_id bigint not null,
id bigint generated by default as identity,
updated_at timestamp(6),
color varchar(255),
make varchar(255) not null,
model varchar(255) not null,
plate_number varchar(255),
primary key (id)
);

create table customers (
is_active boolean not null,
created_at timestamp(6),
email_verified_at timestamp(6),
id bigint generated by default as identity,
updated_at timestamp(6),
avatar varchar(255),
city varchar(255),
email varchar(255),
fcm_token varchar(255),
name varchar(255) not null,
password varchar(255) not null,
phone varchar(255) unique,
primary key (id)
);

create table device_tokens (
created_at timestamp(6),
id bigint generated by default as identity,
updated_at timestamp(6),
user_id bigint not null,
token varchar(255) not null,
user_role varchar(255) not null,
primary key (id)
);

create table drivers (
is_active boolean not null,
is_approved boolean not null,
is_online boolean not null,
latitude float(53),
longitude float(53),
created_at timestamp(6),
email_verified_at timestamp(6),
id bigint generated by default as identity,
updated_at timestamp(6),
city varchar(255),
email varchar(255),
fcm_token varchar(255),
name varchar(255) not null,
password varchar(255) not null,
phone varchar(255) not null unique,
plate_number varchar(255),
service_mode varchar(255),
vehicle_type varchar(255),
primary key (id)
);

create table home_service_assignments (
arrived_at timestamp(6),
assigned_at timestamp(6),
completed_at timestamp(6),
created_at timestamp(6),
en_route_at timestamp(6),
id bigint generated by default as identity,
request_id bigint not null unique,
started_at timestamp(6),
technician_id bigint,
updated_at timestamp(6),
workshop_id bigint not null,
customer_notes TEXT,
status varchar(255) not null,
primary key (id)
);

create table inspection_checklist_items (
sort_order integer,
id bigint generated by default as identity,
report_id bigint not null,
category varchar(255) not null,
image_url varchar(255),
item_name varchar(255) not null,
notes TEXT,
status varchar(255) not null,
primary key (id)
);

create table inspection_labor_items (
hourly_rate float(53) not null,
hours float(53) not null,
total float(53) not null,
id bigint generated by default as identity,
report_id bigint not null,
description varchar(255) not null,
primary key (id)
);

create table inspection_part_items (
quantity integer not null,
total float(53) not null,
unit_price float(53) not null,
id bigint generated by default as identity,
report_id bigint not null,
part_name varchar(255) not null,
primary key (id)
);

create table inspection_reports (
grand_total float(53),
mileage integer,
next_service_date date,
next_service_mileage integer,
tax float(53),
total_labor float(53),
total_parts float(53),
created_at timestamp(6),
id bigint generated by default as identity,
request_id bigint not null,
updated_at timestamp(6),
workshop_id bigint not null,
notes TEXT,
overall_condition varchar(255),
recommendations TEXT,
status varchar(255) not null,
primary key (id)
);

create table invoice_items (
quantity integer not null,
total float(53) not null,
unit_price float(53) not null,
id bigint generated by default as identity,
invoice_id bigint not null,
name varchar(255) not null,
primary key (id)
);

create table invoices (
commission_amount float(53),
commission_percentage float(53),
grand_total float(53),
labor_total float(53),
net_amount float(53),
parts_total float(53),
tax float(53),
total_amount float(53),
created_at timestamp(6),
customer_id bigint not null,
id bigint generated by default as identity,
paid_at timestamp(6),
request_id bigint not null,
settled_at timestamp(6),
settlement_id bigint,
workshop_id bigint not null,
invoice_number varchar(255) not null unique,
payment_id varchar(255),
payment_method varchar(255),
status varchar(255) not null,
primary key (id)
);

create table journal_entries (
entry_date date not null,
created_at timestamp(6),
id bigint generated by default as identity,
reference_id bigint,
entry_number varchar(30) not null unique,
reference_type varchar(30),
description TEXT,
status varchar(255) not null,
primary key (id)
);

create table journal_entry_lines (
credit float(53) not null,
debit float(53) not null,
account_id bigint not null,
entry_id bigint not null,
id bigint generated by default as identity,
description TEXT,
primary key (id)
);

create table maintenance_requests (
allow_multi_workshop boolean,
has_transport_request boolean,
location_lat float(53),
location_lng float(53),
car_id bigint not null,
created_at timestamp(6),
customer_id bigint not null,
id bigint generated by default as identity,
updated_at timestamp(6),
city varchar(255) not null,
description TEXT,
execution_method varchar(255),
location_address varchar(255),
status varchar(255) not null,
primary key (id)
);

create table media (
created_at timestamp(6),
id bigint generated by default as identity,
request_id bigint not null,
thumbnail_url varchar(255),
type varchar(255) not null,
url varchar(255) not null,
primary key (id)
);

create table oauth_accounts (
created_at timestamp(6),
id bigint generated by default as identity,
user_id bigint not null,
provider varchar(20) not null,
user_type varchar(20) not null,
email varchar(255),
name varchar(255),
provider_id varchar(255) not null,
primary key (id)
);

create table payment_holds (
amount float(53) not null,
customer_id bigint not null,
held_at timestamp(6),
id bigint generated by default as identity,
refunded_at timestamp(6),
released_at timestamp(6),
request_id bigint not null,
updated_at timestamp(6),
workshop_id bigint,
status varchar(255) not null,
primary key (id)
);

create table payments (
amount float(53) not null,
fee float(53),
total float(53) not null,
created_at timestamp(6),
customer_id bigint not null,
id bigint generated by default as identity,
request_id bigint not null,
updated_at timestamp(6),
currency varchar(255) not null,
method varchar(255) not null,
moyasar_invoice_id varchar(255),
moyasar_payment_id varchar(255),
status varchar(255) not null,
primary key (id)
);

create table platform_settings (
created_at timestamp(6),
id bigint generated by default as identity,
updated_at timestamp(6),
setting_key varchar(50) not null unique,
description varchar(255),
setting_value TEXT,
primary key (id)
);

create table quotes (
estimated_days integer,
price float(53) not null,
warranty_months integer,
created_at timestamp(6),
id bigint generated by default as identity,
request_id bigint not null,
service_type_id bigint,
workshop_id bigint not null,
notes TEXT,
status varchar(255) not null,
primary key (id)
);

create table refresh_tokens (
revoked boolean not null,
created_at timestamp(6),
expires_at timestamp(6) not null,
id bigint generated by default as identity,
user_id bigint not null,
user_role varchar(20) not null,
token varchar(512) not null unique,
primary key (id)
);

create table request_service_types (
request_id bigint not null,
service_type_id bigint not null
);

create table request_status_history (
created_at timestamp(6),
id bigint generated by default as identity,
request_id bigint not null,
created_by varchar(255),
notes TEXT,
status varchar(255) not null,
primary key (id)
);

create table reviews (
rating integer not null,
created_at timestamp(6),
customer_id bigint not null,
id bigint generated by default as identity,
request_id bigint,
workshop_id bigint not null,
comment TEXT,
primary key (id)
);

create table service_items (
accepted_at timestamp(6),
assigned_at timestamp(6),
completed_at timestamp(6),
created_at timestamp(6),
id bigint generated by default as identity,
request_id bigint not null,
service_type_id bigint not null,
updated_at timestamp(6),
verified_at timestamp(6),
workshop_id bigint,
status varchar(255) not null,
primary key (id)
);

create table service_types (
is_active boolean not null,
id bigint generated by default as identity,
category varchar(255),
description TEXT,
estimated_duration varchar(255),
icon varchar(255),
name varchar(255) not null,
name_en varchar(255),
primary key (id)
);

create table sub_order_items (
item_price float(53),
created_at timestamp(6),
id bigint generated by default as identity,
quote_id bigint,
service_type_id bigint not null,
sub_order_id bigint not null,
status varchar(255) not null,
primary key (id)
);

create table sub_orders (
total_price float(53),
created_at timestamp(6),
id bigint generated by default as identity,
request_id bigint not null,
workshop_id bigint not null,
status varchar(255) not null,
primary key (id)
);

create table technicians (
is_active boolean not null,
is_online boolean not null,
latitude float(53),
longitude float(53),
created_at timestamp(6),
id bigint generated by default as identity,
updated_at timestamp(6),
workshop_id bigint,
email varchar(255),
fcm_token varchar(255),
name varchar(255) not null,
password varchar(255) not null,
phone varchar(255) not null unique,
specialty varchar(255),
primary key (id)
);

create table transport_requests (
distance float(53),
dropoff_lat float(53),
dropoff_lng float(53),
estimated_time integer,
pickup_lat float(53),
pickup_lng float(53),
price float(53),
completed_at timestamp(6),
created_at timestamp(6),
customer_id bigint not null,
driver_id bigint,
id bigint generated by default as identity,
request_id bigint not null,
started_at timestamp(6),
dropoff_address varchar(255),
pickup_address varchar(255),
status varchar(255) not null,
primary key (id)
);

create table workshop_services (
price float(53) not null,
id bigint generated by default as identity,
service_type_id bigint not null,
workshop_id bigint not null,
primary key (id)
);

create table workshop_settlements (
invoice_count integer not null,
total_commission float(53) not null,
total_gross_amount float(53) not null,
total_net_amount float(53) not null,
created_at timestamp(6),
id bigint generated by default as identity,
journal_entry_id bigint,
settled_at timestamp(6),
updated_at timestamp(6),
workshop_id bigint not null,
settlement_number varchar(30) not null unique,
notes TEXT,
status varchar(255) not null,
primary key (id)
);

create table workshops (
is_active boolean not null,
is_approved boolean not null,
latitude float(53),
longitude float(53),
provides_pickup_delivery boolean,
rating float(53) not null,
created_at timestamp(6),
email_verified_at timestamp(6),
id bigint generated by default as identity,
updated_at timestamp(6),
address varchar(255) not null,
city varchar(255) not null,
commercial_registration varchar(255),
email varchar(255),
facebook_url varchar(255),
fcm_token varchar(255),
municipality_license varchar(255),
name varchar(255) not null,
owner_name varchar(255),
password varchar(255) not null,
phone varchar(255) not null unique,
rejection_reason varchar(255),
services TEXT,
snapchat_url varchar(255),
tiktok_url varchar(255),
working_hours varchar(255),
workshop_type varchar(255),
primary key (id)
);

alter table if exists accounts 
add constraint FK7iek2tl1ntnp3yyks15odo4h2 
foreign key (parent_id) 
references accounts;

alter table if exists chat_messages 
add constraint FKhalwepod3944695ji0suwoqb9 
foreign key (room_id) 
references chat_rooms;

alter table if exists chat_rooms 
add constraint FKg7i16vb314i2vhhj273ve36c4 
foreign key (customer_id) 
references customers;

alter table if exists chat_rooms 
add constraint FKjedbe4synbahkof4ukxaa1bj6 
foreign key (driver_id) 
references drivers;

alter table if exists chat_rooms 
add constraint FKhh78pf6qqsdl85871o75lnjwn 
foreign key (request_id) 
references maintenance_requests;

alter table if exists chat_rooms 
add constraint FK5fn44k8pdkvk7m3r6g7pq9l61 
foreign key (workshop_id) 
references workshops;

alter table if exists customer_cars 
add constraint FKfe16lld6hauk8g73ra4n47ha7 
foreign key (customer_id) 
references customers;

alter table if exists home_service_assignments 
add constraint FKrp2tgd4i9rvoo5uf8rb466q0g 
foreign key (request_id) 
references maintenance_requests;

alter table if exists home_service_assignments 
add constraint FKmhp9csmw8p7gsepvnp9k6tgoi 
foreign key (technician_id) 
references technicians;

alter table if exists home_service_assignments 
add constraint FKp7emyqhby0p5ukudrlf5wo6ja 
foreign key (workshop_id) 
references workshops;

alter table if exists inspection_checklist_items 
add constraint FKsta178vxstbt784t9d2bjfhqt 
foreign key (report_id) 
references inspection_reports;

alter table if exists inspection_labor_items 
add constraint FKf0210a5p559hlcwc9picgvs48 
foreign key (report_id) 
references inspection_reports;

alter table if exists inspection_part_items 
add constraint FKexygej1xogjd9ojma9lkes02p 
foreign key (report_id) 
references inspection_reports;

alter table if exists inspection_reports 
add constraint FKai78iy331oa6t7x4wjerll5pb 
foreign key (request_id) 
references maintenance_requests;

alter table if exists inspection_reports 
add constraint FK7bt4gne2vtojvhdh44ffpv91y 
foreign key (workshop_id) 
references workshops;

alter table if exists invoice_items 
add constraint FK46ae0lhu1oqs7cv91fn6y9n7w 
foreign key (invoice_id) 
references invoices;

alter table if exists invoices 
add constraint FKq2w4hmh6l9othnp6cepp0cfe2 
foreign key (customer_id) 
references customers;

alter table if exists invoices 
add constraint FKb5yvto9jjw5j54ngaewm0c6td 
foreign key (request_id) 
references maintenance_requests;

alter table if exists invoices 
add constraint FKt4w9pgf74f6t1lx044i537xvy 
foreign key (settlement_id) 
references workshop_settlements;

alter table if exists invoices 
add constraint FKqxuqbnmpi5b9uf2uxc5gy4vls 
foreign key (workshop_id) 
references workshops;

alter table if exists journal_entry_lines 
add constraint FK3t3uhyexb3kw2t2xid4fjn9wx 
foreign key (account_id) 
references accounts;

alter table if exists journal_entry_lines 
add constraint FKey9npn3nwyirq4gn64dbnccxi 
foreign key (entry_id) 
references journal_entries;

alter table if exists maintenance_requests 
add constraint FKgyjuebv573gx0fpnwa91wksyh 
foreign key (car_id) 
references customer_cars;

alter table if exists maintenance_requests 
add constraint FK3fratk45m8332y3eph0qwsx7a 
foreign key (customer_id) 
references customers;

alter table if exists media 
add constraint FKgh4oxfr5w52nefu83agm1b9r7 
foreign key (request_id) 
references maintenance_requests;

alter table if exists payment_holds 
add constraint FKt7kk4yfx2skewv70csfhy0e26 
foreign key (customer_id) 
references customers;

alter table if exists payment_holds 
add constraint FKqaxerqifu4gm8dvn5ydwu3j0b 
foreign key (request_id) 
references maintenance_requests;

alter table if exists payment_holds 
add constraint FKrs9ffr01gvuaahonus7l97pnq 
foreign key (workshop_id) 
references workshops;

alter table if exists payments 
add constraint FK45dp0030s8e3myd8n6ky4e79g 
foreign key (customer_id) 
references customers;

alter table if exists payments 
add constraint FK8clu25nl7b5kjh0v2psa4d4e3 
foreign key (request_id) 
references maintenance_requests;

alter table if exists quotes 
add constraint FK5p7g6eujh2ms1ycjvmm37088c 
foreign key (request_id) 
references maintenance_requests;

alter table if exists quotes 
add constraint FKrh2e27s8fffsh6m2fe42060c2 
foreign key (service_type_id) 
references service_types;

alter table if exists quotes 
add constraint FK1cb6e8up3cjn6ysdm1t1ejw5w 
foreign key (workshop_id) 
references workshops;

alter table if exists request_service_types 
add constraint FKbvkm1pjt0khgk8i0xupht887 
foreign key (service_type_id) 
references service_types;

alter table if exists request_service_types 
add constraint FKj09inkl9p5ucqicf14ptjsp35 
foreign key (request_id) 
references maintenance_requests;

alter table if exists request_status_history 
add constraint FKscnuekiupeqmt5ikdyv9t5h5u 
foreign key (request_id) 
references maintenance_requests;

alter table if exists reviews 
add constraint FK4sm0k8kw740iyuex3vwwv1etu 
foreign key (customer_id) 
references customers;

alter table if exists reviews 
add constraint FKrdnkht6yoj8a8741sxwgihs4d 
foreign key (request_id) 
references maintenance_requests;

alter table if exists reviews 
add constraint FKidwjlv928vuygfulx92udy3tg 
foreign key (workshop_id) 
references workshops;

alter table if exists service_items 
add constraint FKs3576tdykn049b09ak4gr3lew 
foreign key (request_id) 
references maintenance_requests;

alter table if exists service_items 
add constraint FK3aj2aglxdlbx4nwoq9graxip9 
foreign key (service_type_id) 
references service_types;

alter table if exists service_items 
add constraint FKis65loex8lh0iya51doyhei7h 
foreign key (workshop_id) 
references workshops;

alter table if exists sub_order_items 
add constraint FKekibbhpxj4uyml4alxbk4tuuf 
foreign key (quote_id) 
references quotes;

alter table if exists sub_order_items 
add constraint FKhlmjgr330mlel79h27fvx5mbv 
foreign key (service_type_id) 
references service_types;

alter table if exists sub_order_items 
add constraint FK5v0m24lqb26wr46210sdxhduu 
foreign key (sub_order_id) 
references sub_orders;

alter table if exists sub_orders 
add constraint FK53exbcyg8xe6pe64xulng07ta 
foreign key (request_id) 
references maintenance_requests;

alter table if exists sub_orders 
add constraint FKtcx22vbuir2iqlarab4jp3ujo 
foreign key (workshop_id) 
references workshops;

alter table if exists technicians 
add constraint FKtp3q2oslbkk29bto1qh6mo4s7 
foreign key (workshop_id) 
references workshops;

alter table if exists transport_requests 
add constraint FK7abpufh065suaw6ddtnwse7ib 
foreign key (customer_id) 
references customers;

alter table if exists transport_requests 
add constraint FK6vs1jinwvuk7y1op1q03xf7ul 
foreign key (driver_id) 
references drivers;

alter table if exists transport_requests 
add constraint FKtf88oyubmwjs3ux60ielfj1h5 
foreign key (request_id) 
references maintenance_requests;

alter table if exists workshop_services 
add constraint FKbi98us6kq64jj8jhnq06589ua 
foreign key (service_type_id) 
references service_types;

alter table if exists workshop_services 
add constraint FK2owh0mscoujimjwqcka31xw1x 
foreign key (workshop_id) 
references workshops;

alter table if exists workshop_settlements 
add constraint FKhtid9ai684epkk40959bxe8dk 
foreign key (journal_entry_id) 
references journal_entries;

alter table if exists workshop_settlements 
add constraint FK2gpr5jflwt6hg2jg133qkl2nl 
foreign key (workshop_id) 
references workshops;

-- Performance indexes on all foreign key columns
create index if not exists idx_chat_messages_room_id on chat_messages(room_id);
create index if not exists idx_chat_messages_sender_id on chat_messages(sender_id);
create index if not exists idx_chat_rooms_customer_id on chat_rooms(customer_id);
create index if not exists idx_chat_rooms_driver_id on chat_rooms(driver_id);
create index if not exists idx_chat_rooms_request_id on chat_rooms(request_id);
create index if not exists idx_chat_rooms_workshop_id on chat_rooms(workshop_id);
create index if not exists idx_customer_cars_customer_id on customer_cars(customer_id);
create index if not exists idx_home_service_assignments_request_id on home_service_assignments(request_id);
create index if not exists idx_home_service_assignments_technician_id on home_service_assignments(technician_id);
create index if not exists idx_home_service_assignments_workshop_id on home_service_assignments(workshop_id);
create index if not exists idx_inspection_reports_request_id on inspection_reports(request_id);
create index if not exists idx_inspection_reports_workshop_id on inspection_reports(workshop_id);
create index if not exists idx_invoice_items_invoice_id on invoice_items(invoice_id);
create index if not exists idx_invoices_customer_id on invoices(customer_id);
create index if not exists idx_invoices_request_id on invoices(request_id);
create index if not exists idx_invoices_settlement_id on invoices(settlement_id);
create index if not exists idx_invoices_workshop_id on invoices(workshop_id);
create index if not exists idx_journal_entry_lines_account_id on journal_entry_lines(account_id);
create index if not exists idx_journal_entry_lines_entry_id on journal_entry_lines(entry_id);
create index if not exists idx_maintenance_requests_car_id on maintenance_requests(car_id);
create index if not exists idx_maintenance_requests_customer_id on maintenance_requests(customer_id);
create index if not exists idx_media_request_id on media(request_id);
create index if not exists idx_oauth_accounts_user_id on oauth_accounts(user_id);
create index if not exists idx_payment_holds_customer_id on payment_holds(customer_id);
create index if not exists idx_payment_holds_request_id on payment_holds(request_id);
create index if not exists idx_payment_holds_workshop_id on payment_holds(workshop_id);
create index if not exists idx_payments_customer_id on payments(customer_id);
create index if not exists idx_payments_request_id on payments(request_id);
create index if not exists idx_quotes_request_id on quotes(request_id);
create index if not exists idx_quotes_service_type_id on quotes(service_type_id);
create index if not exists idx_quotes_workshop_id on quotes(workshop_id);
create index if not exists idx_reviews_customer_id on reviews(customer_id);
create index if not exists idx_reviews_request_id on reviews(request_id);
create index if not exists idx_reviews_workshop_id on reviews(workshop_id);
create index if not exists idx_request_service_types_request_id on request_service_types(request_id);
create index if not exists idx_request_service_types_service_type_id on request_service_types(service_type_id);
create index if not exists idx_service_items_request_id on service_items(request_id);
create index if not exists idx_service_items_service_type_id on service_items(service_type_id);
create index if not exists idx_service_items_workshop_id on service_items(workshop_id);
create index if not exists idx_sub_order_items_quote_id on sub_order_items(quote_id);
create index if not exists idx_sub_order_items_service_type_id on sub_order_items(service_type_id);
create index if not exists idx_sub_order_items_sub_order_id on sub_order_items(sub_order_id);
create index if not exists idx_sub_orders_request_id on sub_orders(request_id);
create index if not exists idx_sub_orders_workshop_id on sub_orders(workshop_id);
create index if not exists idx_technicians_workshop_id on technicians(workshop_id);
create index if not exists idx_transport_requests_customer_id on transport_requests(customer_id);
create index if not exists idx_transport_requests_driver_id on transport_requests(driver_id);
create index if not exists idx_transport_requests_request_id on transport_requests(request_id);
create index if not exists idx_workshop_services_service_type_id on workshop_services(service_type_id);
create index if not exists idx_workshop_services_workshop_id on workshop_services(workshop_id);
create index if not exists idx_workshop_settlements_journal_entry_id on workshop_settlements(journal_entry_id);
create index if not exists idx_workshop_settlements_workshop_id on workshop_settlements(workshop_id);

-- Unique constraints on email columns for user tables
alter table if exists customers add constraint if not exists uk_customers_email unique (email);
alter table if exists workshops add constraint if not exists uk_workshops_email unique (email);
alter table if exists drivers add constraint if not exists uk_drivers_email unique (email);
alter table if exists technicians add constraint if not exists uk_technicians_email unique (email);

-- Unique constraint on request_service_types to prevent duplicate service type assignments
alter table if exists request_service_types add constraint if not exists uk_request_service_types unique (request_id, service_type_id);

-- CHECK constraints for data integrity
alter table if exists workshops add constraint if not exists chk_workshops_rating check (rating >= 0 and rating <= 5);
alter table if exists customer_cars add constraint if not exists chk_customer_cars_year check (car_year >= 1900 and car_year <= 2100);
alter table if exists invoice_items add constraint if not exists chk_invoice_items_quantity check (quantity > 0);
alter table if exists reviews add constraint if not exists chk_reviews_rating check (rating >= 1 and rating <= 5);
alter table if exists workshop_settlements add constraint if not exists chk_settlements_invoice_count check (invoice_count >= 0);
alter table if exists accounts add constraint if not exists chk_accounts_level check (level >= 0);
